#!/usr/bin/env python3
"""font.json -> plot/font_maple.odin: static single-line glyph data.

Each stroke is a flat point list: p0, then (c1, c2, p) per cubic segment,
so len(points) == 1 + 3*segments. A single point is a pen-down dot.
Coordinates are em-normalized, y-down, baseline at y = 0, advance 0.6.
"""

import json
import os
import sys

REPO = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
OUT = os.path.join(REPO, "plot", "font_maple.odin")


def fnum(v):
    s = f"{v:.4f}".rstrip("0").rstrip(".")
    return s if s else "0"


def main():
    src = sys.argv[1] if len(sys.argv) > 1 else os.path.join(os.path.dirname(os.path.abspath(__file__)), "font.json")
    with open(src) as f:
        font = json.load(f)
    glyphs = font["glyphs"]

    lines = []
    lines.append("package plot")
    lines.append("")
    lines.append("// Generated by tools/singleline_font from MapleMono-Thin.ttf -- do not edit.")
    lines.append("// Maple Mono is (c) subframe7536, SIL Open Font License 1.1.")
    lines.append("// Single-line derivative for pen plotting; coordinates are fractions of the em,")
    lines.append("// y-down, baseline at y = 0.")
    lines.append("")
    lines.append("FONT_ADVANCE :: f32(0.6)")
    lines.append("FONT_CAP_HEIGHT :: f32(0.73)")
    lines.append("FONT_X_HEIGHT :: f32(0.55)")
    lines.append("FONT_ASCENT :: f32(1.02)")
    lines.append("FONT_DESCENT :: f32(0.3)")
    lines.append("FONT_LINE_HEIGHT :: f32(1.32)")
    lines.append("")
    lines.append("Glyph_Stroke :: struct {")
    lines.append("\tpoints: []Vec2, // p0 then (c1, c2, p) per cubic; a single point is a dot")
    lines.append("\tclosed: bool,")
    lines.append("}")
    lines.append("")
    def stroke_lines(g, indent):
        out = []
        for st in g["strokes"]:
            if "dot" in st:
                x, y = st["dot"]
                out.append(f"{indent}{{points = {{{{{fnum(x)}, {fnum(y)}}}}}}},")
                continue
            pts = []
            cubics = st["cubics"]
            pts.append(tuple(cubics[0][0]))
            for b in cubics:
                pts.append(tuple(b[1]))
                pts.append(tuple(b[2]))
                pts.append(tuple(b[3]))
            body = ", ".join(f"{{{fnum(x)}, {fnum(y)}}}" for x, y in pts)
            closed = ", closed = true" if st.get("closed") else ""
            out.append(f"{indent}{{points = {{{body}}}{closed}}},")
        return out

    lines.append("// Printable ASCII 33..126, indexed by char - 33")
    lines.append("font_glyphs := [94][]Glyph_Stroke{")

    for code in range(33, 127):
        ch = chr(code)
        g = glyphs.get(ch)
        label = ch if ch != "'" else "\\'"
        if g is None or not g["strokes"]:
            lines.append(f"\t{{}}, // '{label}'")
            continue
        lines.append(f"\t{{ // '{label}'")
        lines.extend(stroke_lines(g, "\t\t"))
        lines.append("\t},")
    lines.append("}")
    lines.append("")

    ext = sorted((ch for ch in glyphs if not (33 <= ord(ch) <= 126)), key=ord)
    ext = [ch for ch in ext if glyphs[ch]["strokes"]]
    lines.append("Ext_Glyph :: struct {")
    lines.append("\tch: rune,")
    lines.append("\tstrokes: []Glyph_Stroke,")
    lines.append("}")
    lines.append("")
    lines.append("// Non-ASCII glyphs, sorted by codepoint (glyph_strokes binary-searches)")
    lines.append(f"font_glyphs_ext := [{len(ext)}]Ext_Glyph{{")
    for ch in ext:
        lines.append(f"\t{{ch = {hex(ord(ch))}, strokes = {{ // '{ch}'")
        lines.extend(stroke_lines(glyphs[ch], "\t\t"))
        lines.append("\t}},")
    lines.append("}")
    lines.append("")

    with open(OUT, "w") as f:
        f.write("\n".join(lines))
    print(f"wrote {OUT} ({len(lines)} lines)")


if __name__ == "__main__":
    main()
